# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2b3668250b7b9314d68208f54f7ed74d22bd54a7c05b4f9a53a4dc85c6edb08d52b78cce65f8b078179006af0f5cb880664cb9f1f06b35151eca510e2d2edb

test:
  secret_key_base: 01a72325c548071df4713080cfd49572659014f6d4e1d4e4e35e75cde160eb709a91a400b5582f5865f353895920579aaa10fe5ab9b78ef1fd04c1a60b87a78a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
